"""Phase 4 -- put every capture into one comparable coordinate frame.

Full rationale and the exact maths: docs/NORMALIZATION.md.

The pipeline in brief
---------------------
    raw vertices
      -> [1] to face-local space   (exact; undoes camera distance and head pose)
      -> [2] to the canonical Looksmatch frame  (signed axis permutation)
      -> [3] translate to a chosen origin
      -> [4] divide by a chosen scale reference
      -> [5] optional Procrustes refinement against a cohort mean shape

Why step [1] is exact, not estimated
------------------------------------
``ARFaceGeometry.vertices`` are expressed relative to the ``ARFaceAnchor``, not
to the camera. ARKit has already solved head pose, so a face-local capture is
ALREADY free of camera distance, translation and rotation. There is nothing to
estimate. If the exporter baked the anchor transform into the vertices (i.e.
exported world space), we invert that transform to get back.

So "rotation normalisation" here is not a fitting problem -- it is a matter of
knowing which ARKit axis is which, which is a fixed property of the format. That
is DETECTED ONCE from your real data (with reported evidence you can eyeball),
never assumed. See :class:`AxisConvention`.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
from scipy.spatial import cKDTree

from .config import CONFIG_DIR, RAW_DIR, ensure_dirs
from .data_loader import FaceCapture, load_all, load_capture

AXES_PATH = CONFIG_DIR / "axis_convention.json"

# Canonical Looksmatch frame, right-handed:
#   +X = subject's LEFT      +Y = superior (up)      +Z = anterior (out of face)
# Check: X x Y = Z holds for (left, up, anterior) when viewed from in front.
CANONICAL_AXES = ("left", "superior", "anterior")


# ==========================================================================
# Axis convention
# ==========================================================================

@dataclass
class AxisConvention:
    """Which raw ARKit axis (and sign) corresponds to each canonical direction.

    ``left = (axis_index, sign)`` means: canonical +X (subject's left) equals
    ``sign * raw[:, axis_index]``.
    """

    left: tuple[int, int]
    superior: tuple[int, int]
    anterior: tuple[int, int]
    evidence: dict = field(default_factory=dict)
    confirmed_by_user: bool = False

    # -- matrix form -------------------------------------------------------

    def matrix(self) -> np.ndarray:
        """``(3, 3)`` matrix R with ``canonical = raw @ R.T``."""
        rot = np.zeros((3, 3), dtype=np.float64)
        for row, (axis, sign) in enumerate((self.left, self.superior, self.anterior)):
            rot[row, axis] = float(sign)
        return rot

    def is_right_handed(self) -> bool:
        return bool(np.linalg.det(self.matrix()) > 0)

    def apply(self, points: np.ndarray) -> np.ndarray:
        return np.asarray(points, dtype=np.float64) @ self.matrix().T

    # -- persistence -------------------------------------------------------

    def to_dict(self) -> dict:
        return {
            "_README": (
                "Which raw ARKit axis maps to each canonical Looksmatch direction. "
                "Canonical frame is right-handed: +X subject's left, +Y superior, "
                "+Z anterior. Format: [raw_axis_index, sign]. Generated by "
                "`python -m src.normalization detect`; set confirmed_by_user true "
                "once you have eyeballed the result in the 3D viewer."
            ),
            "left": list(self.left),
            "superior": list(self.superior),
            "anterior": list(self.anterior),
            "confirmed_by_user": self.confirmed_by_user,
            "evidence": self.evidence,
        }

    def save(self, path: Path | None = None) -> Path:
        path = path or AXES_PATH
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")
        return path

    @classmethod
    def load(cls, path: Path | None = None) -> "AxisConvention | None":
        path = path or AXES_PATH
        if not path.exists():
            return None
        blob = json.loads(path.read_text(encoding="utf-8"))
        return cls(
            left=tuple(blob["left"]),
            superior=tuple(blob["superior"]),
            anterior=tuple(blob["anterior"]),
            evidence=blob.get("evidence", {}),
            confirmed_by_user=bool(blob.get("confirmed_by_user", False)),
        )

    def describe(self) -> str:
        names = "XYZ"
        parts = [
            f"  subject's left  = {'+' if s > 0 else '-'}{names[a]}"
            for a, s in (self.left,)
        ]
        parts.append(f"  superior (up)   = {'+' if self.superior[1] > 0 else '-'}{names[self.superior[0]]}")
        parts.append(f"  anterior (out)  = {'+' if self.anterior[1] > 0 else '-'}{names[self.anterior[0]]}")
        parts.append(f"  right-handed    = {self.is_right_handed()}")
        return "\n".join(parts)


def _mirror_symmetry_error(points: np.ndarray, axis: int) -> float:
    """RMS nearest-neighbour error after mirroring across the plane normal to
    ``axis`` through the centroid, normalised by centroid size.

    Low error means the mesh is bilaterally symmetric about that axis, which is
    what identifies the left-right axis of a face.
    """
    centred = points - points.mean(axis=0)
    scale = float(np.sqrt((centred ** 2).sum(axis=1).mean()))
    if scale == 0:
        return np.inf
    mirrored = centred.copy()
    mirrored[:, axis] *= -1.0
    distances, _ = cKDTree(centred).query(mirrored, k=1)
    return float(np.sqrt((distances ** 2).mean()) / scale)


def _skewness(values: np.ndarray) -> float:
    centred = values - values.mean()
    sigma = centred.std()
    return float((centred ** 3).mean() / sigma ** 3) if sigma > 0 else 0.0


def detect_axis_convention(captures: Sequence[FaceCapture]) -> AxisConvention:
    """Work out the ARKit axis convention from real captures, with evidence.

    Detection rules, in order of reliability:

    LEFT-RIGHT axis
        The axis whose mirror plane leaves the mesh most self-similar (faces are
        bilaterally symmetric; the other two axes are not). Decided by
        :func:`_mirror_symmetry_error`, which is a property of the geometry, not
        an assumption.
    LEFT-RIGHT sign
        From ``ARFaceAnchor.leftEyeTransform`` vs ``rightEyeTransform`` when the
        export has them -- these are named by Apple, so the sign is definitive.
        WITHOUT them the sign is UNRESOLVED: we pick one and flag it, and
        side-specific ("left cheek" vs "right cheek") features are suppressed
        because they would be mirrored. Bilateral and midline features are
        unaffected.
    ANTERIOR axis and sign
        Of the two remaining axes, the nose is a protruding tail, so the
        anterior axis is the one with the larger absolute skewness, and the tail
        points anteriorly (sign = sign of the skew).
    SUPERIOR axis and sign
        The remaining axis. Sign from the eye midpoint sitting above the mesh
        centroid when eye transforms exist; otherwise from the face being
        broader superiorly (forehead/cheekbones) than inferiorly (the chin
        tapers).
    """
    if not captures:
        raise ValueError("need at least one capture to detect the axis convention")

    evidence: dict = {"n_captures": len(captures)}

    # ---- left-right axis: bilateral symmetry ----------------------------
    sym_errors = np.zeros(3)
    for capture in captures:
        local = to_face_local(capture)
        for axis in range(3):
            sym_errors[axis] += _mirror_symmetry_error(local, axis)
    sym_errors /= len(captures)
    lr_axis = int(np.argmin(sym_errors))
    evidence["mirror_symmetry_error_per_axis"] = [round(float(v), 5) for v in sym_errors]
    evidence["left_right_axis"] = lr_axis
    ordered = np.sort(sym_errors)
    # How decisively the best axis beat the runner-up. Capped for readability:
    # a synthetically perfect mesh drives the denominator to ~0 and the ratio to
    # ~1e14, which is noise in the report rather than information.
    margin = float(ordered[1] / ordered[0]) if ordered[0] > 1e-12 else float("inf")
    evidence["left_right_margin"] = round(margin, 3) if margin < 1e6 else ">1e6 (near-perfect symmetry)"

    # ---- left-right sign: eye transforms are definitive ------------------
    lr_sign = 1
    eye_votes: list[float] = []
    for capture in captures:
        eyes = capture.eye_positions()
        if eyes is None:
            continue
        left_eye, right_eye = eyes
        eye_votes.append(float(left_eye[lr_axis] - right_eye[lr_axis]))
    if eye_votes:
        lr_sign = 1 if float(np.mean(eye_votes)) > 0 else -1
        evidence["left_right_sign_source"] = "ARFaceAnchor eye transforms"
        evidence["left_right_sign_votes"] = len(eye_votes)
        evidence["left_right_sign_agreement"] = round(
            float(np.mean([np.sign(v) == np.sign(np.mean(eye_votes)) for v in eye_votes])), 3
        )
    else:
        evidence["left_right_sign_source"] = "UNRESOLVED (no eye transforms in export)"
        evidence["left_right_sign_warning"] = (
            "Subject-left vs subject-right cannot be distinguished from geometry alone. "
            "Side-specific features are suppressed. Export leftEyeTransform/rightEyeTransform "
            "from the iOS app to resolve this."
        )

    # ---- anterior axis: the nose is a skewed tail ------------------------
    remaining = [a for a in range(3) if a != lr_axis]
    skews = {}
    for axis in remaining:
        skews[axis] = float(np.mean([_skewness(to_face_local(c)[:, axis]) for c in captures]))
    ant_axis = max(remaining, key=lambda a: abs(skews[a]))
    ant_sign = 1 if skews[ant_axis] > 0 else -1
    evidence["skewness_per_remaining_axis"] = {str(a): round(v, 4) for a, v in skews.items()}
    evidence["anterior_axis"] = ant_axis

    # ---- superior axis: whatever is left --------------------------------
    sup_axis = [a for a in remaining if a != ant_axis][0]
    sup_sign = 1
    eye_above: list[float] = []
    for capture in captures:
        eyes = capture.eye_positions()
        if eyes is None:
            continue
        local = to_face_local(capture)
        midpoint = (eyes[0] + eyes[1]) / 2.0
        eye_above.append(float(midpoint[sup_axis] - local[:, sup_axis].mean()))
    if eye_above:
        sup_sign = 1 if float(np.mean(eye_above)) > 0 else -1
        evidence["superior_sign_source"] = "eye midpoint above mesh centroid"
    else:
        # Fall back on taper: the face is broader at the forehead than the chin.
        taper_votes = []
        for capture in captures:
            local = to_face_local(capture)
            coord = local[:, sup_axis]
            width = np.abs(local[:, lr_axis])
            high = coord >= np.quantile(coord, 0.75)
            low = coord <= np.quantile(coord, 0.25)
            taper_votes.append(float(width[high].mean() - width[low].mean()))
        sup_sign = 1 if float(np.mean(taper_votes)) > 0 else -1
        evidence["superior_sign_source"] = "broader end of the mesh taken as superior (forehead vs chin)"
        evidence["superior_taper_margin"] = round(float(np.mean(taper_votes)), 6)

    convention = AxisConvention(
        left=(lr_axis, lr_sign),
        superior=(sup_axis, sup_sign),
        anterior=(ant_axis, ant_sign),
        evidence=evidence,
    )

    # Keep the frame right-handed; if the detected signs make it left-handed,
    # the anterior sign is the one we are least sure of, so flip that.
    if not convention.is_right_handed():
        convention.anterior = (ant_axis, -ant_sign)
        convention.evidence["anterior_sign_flipped_for_handedness"] = True

    return convention


def default_axis_convention() -> AxisConvention | None:
    """The saved convention, or ``None`` if detection has not been run."""
    return AxisConvention.load()


# ==========================================================================
# Normalisation
# ==========================================================================

ORIGIN_MODES = ("centroid", "eye_midpoint", "nose_tip_extremum")
SCALE_MODES = ("centroid_size", "interocular", "none")


@dataclass
class NormalizationConfig:
    """Choices that define the normalised frame. Recorded with every output."""

    origin: str = "centroid"
    scale: str = "centroid_size"
    procrustes: bool = False

    def __post_init__(self) -> None:
        if self.origin not in ORIGIN_MODES:
            raise ValueError(f"origin must be one of {ORIGIN_MODES}, got {self.origin!r}")
        if self.scale not in SCALE_MODES:
            raise ValueError(f"scale must be one of {SCALE_MODES}, got {self.scale!r}")


@dataclass
class NormalizedFace:
    """A capture expressed in the canonical frame, plus full provenance."""

    participant_id: str
    capture_id: str
    vertices: np.ndarray           # (N, 3) in the canonical frame
    triangles: np.ndarray
    scale_reference_m: float       # the divisor used, in metres
    scale_mode: str
    origin_mode: str
    origin_offset_m: np.ndarray    # what was subtracted, pre-scaling, in metres
    axis_convention: AxisConvention
    side_resolved: bool
    eye_positions: tuple[np.ndarray, np.ndarray] | None = None
    notes: list[str] = field(default_factory=list)

    @property
    def key(self) -> str:
        return f"{self.participant_id}/{self.capture_id}"

    def in_metres(self) -> np.ndarray:
        """Undo the scale division: canonical orientation, true metric size."""
        return self.vertices * self.scale_reference_m


def to_face_local(capture: FaceCapture) -> np.ndarray:
    """Vertices in ARKit face-anchor space.

    If the exporter already wrote face-local vertices (ARKit's native output)
    this is a copy. If it wrote world-space vertices, the anchor transform is
    inverted to undo camera pose and distance.
    """
    verts = np.asarray(capture.vertices, dtype=np.float64)
    if capture.coordinate_space != "world":
        return verts.copy()
    if capture.transform is None:
        raise ValueError(
            f"{capture.key}: vertices are declared world-space but no anchor transform "
            "was exported, so head pose cannot be undone."
        )
    inverse = np.linalg.inv(capture.transform)
    homogeneous = np.column_stack([verts, np.ones(len(verts))])
    return (homogeneous @ inverse.T)[:, :3]


def _eye_positions_canonical(capture: FaceCapture, convention: AxisConvention) -> tuple[np.ndarray, np.ndarray] | None:
    eyes = capture.eye_positions()
    if eyes is None:
        return None
    return convention.apply(eyes[0]), convention.apply(eyes[1])


def normalize_capture(
    capture: FaceCapture,
    convention: AxisConvention | None = None,
    config: NormalizationConfig | None = None,
) -> NormalizedFace:
    """Apply steps [1]-[4] of the normalisation pipeline to one capture."""
    config = config or NormalizationConfig()
    if convention is None:
        convention = default_axis_convention()
        if convention is None:
            raise ValueError(
                "No axis convention available. Run `python -m src.normalization detect` "
                "once on your real captures first (it writes config/axis_convention.json)."
            )

    notes: list[str] = []
    if not convention.confirmed_by_user:
        notes.append("axis convention not yet visually confirmed (see docs/NORMALIZATION.md)")

    # [1] face-local, [2] canonical axes
    local = to_face_local(capture)
    verts = convention.apply(local)
    eyes = _eye_positions_canonical(capture, convention)
    side_resolved = bool(capture.has_eye_transforms()) or "UNRESOLVED" not in str(
        convention.evidence.get("left_right_sign_source", "")
    )
    if not side_resolved:
        notes.append("subject left/right unresolved; side-specific features suppressed")

    # [3] origin
    if config.origin == "centroid":
        origin = verts.mean(axis=0)
    elif config.origin == "eye_midpoint":
        if eyes is None:
            raise ValueError(
                f"{capture.key}: origin='eye_midpoint' needs eye transforms, which this "
                "export does not contain. Use origin='centroid'."
            )
        origin = (eyes[0] + eyes[1]) / 2.0
    else:  # nose_tip_extremum
        origin = verts[int(np.argmax(verts[:, 2]))].copy()
        notes.append("origin at the most anterior vertex (geometric extremum, not a picked landmark)")
    verts = verts - origin
    if eyes is not None:
        eyes = (eyes[0] - origin, eyes[1] - origin)

    # [4] scale
    if config.scale == "centroid_size":
        # Root-mean-square distance to the centroid: the standard scale measure
        # in geometric morphometrics. Uses every vertex, so no single noisy
        # point can move it, and it needs no landmarks.
        centred = verts - verts.mean(axis=0)
        reference = float(np.sqrt((centred ** 2).sum(axis=1).mean()))
    elif config.scale == "interocular":
        if eyes is None:
            raise ValueError(
                f"{capture.key}: scale='interocular' needs eye transforms, which this "
                "export does not contain. Use scale='centroid_size'."
            )
        reference = float(np.linalg.norm(eyes[0] - eyes[1]))
    else:
        reference = 1.0
        notes.append("no scale normalisation: values stay in metres")

    if reference <= 0:
        raise ValueError(f"{capture.key}: scale reference is {reference}, cannot normalise")
    verts = verts / reference
    if eyes is not None:
        eyes = (eyes[0] / reference, eyes[1] / reference)

    return NormalizedFace(
        participant_id=capture.participant_id,
        capture_id=capture.capture_id,
        vertices=verts,
        triangles=capture.triangles.copy(),
        scale_reference_m=reference,
        scale_mode=config.scale,
        origin_mode=config.origin,
        origin_offset_m=origin,
        axis_convention=convention,
        side_resolved=side_resolved,
        eye_positions=eyes,
        notes=notes,
    )


# -- step [5]: optional Procrustes refinement ------------------------------

def procrustes_align(source: np.ndarray, target: np.ndarray) -> np.ndarray:
    """Rotate ``source`` onto ``target`` (rotation only, no scale/reflection).

    Correspondence is by vertex INDEX, which is exact here because every capture
    in a cohort shares one ARKit topology. Classic Kabsch/orthogonal Procrustes,
    with the determinant correction that forbids reflection -- reflecting a face
    would swap its left and right sides.
    """
    src_c = source - source.mean(axis=0)
    tgt_c = target - target.mean(axis=0)
    u, _, vt = np.linalg.svd(src_c.T @ tgt_c)
    d = np.sign(np.linalg.det(vt.T @ u.T))
    correction = np.diag([1.0, 1.0, d])
    rotation = vt.T @ correction @ u.T
    return src_c @ rotation.T


def generalized_procrustes(
    faces: Sequence[NormalizedFace], iterations: int = 3, tol: float = 1e-7
) -> tuple[list[NormalizedFace], np.ndarray]:
    """Iteratively align a cohort to its own mean shape (rotation only).

    This removes RESIDUAL orientation jitter left by ARKit's tracker. It is a
    refinement of an already-good alignment, not the primary pose normalisation
    -- that came free from the face-anchor frame.
    """
    if not faces:
        return [], np.zeros((0, 3))
    counts = {f.vertices.shape[0] for f in faces}
    if len(counts) != 1:
        raise ValueError(f"Procrustes needs one shared topology; found vertex counts {counts}")

    aligned = [f.vertices.copy() for f in faces]
    mean_shape = aligned[0].copy()
    for _ in range(iterations):
        aligned = [procrustes_align(v, mean_shape) for v in aligned]
        new_mean = np.mean(aligned, axis=0)
        shift = float(np.linalg.norm(new_mean - mean_shape))
        mean_shape = new_mean
        if shift < tol:
            break

    out: list[NormalizedFace] = []
    for face, verts in zip(faces, aligned):
        refined = NormalizedFace(**{**face.__dict__, "vertices": verts})
        refined.notes = list(face.notes) + ["generalized Procrustes refinement applied"]
        out.append(refined)
    return out, mean_shape


def normalize_all(
    captures: Iterable[FaceCapture],
    convention: AxisConvention | None = None,
    config: NormalizationConfig | None = None,
) -> list[NormalizedFace]:
    config = config or NormalizationConfig()
    faces = [normalize_capture(c, convention, config) for c in captures]
    if config.procrustes and faces:
        faces, _ = generalized_procrustes(faces)
    return faces


# ==========================================================================
# CLI
# ==========================================================================

def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Detect the axis convention and normalise captures.")
    sub = parser.add_subparsers(dest="command", required=True)

    p_detect = sub.add_parser("detect", help="detect the ARKit axis convention from real captures")
    p_detect.add_argument("root", nargs="?", default=str(RAW_DIR))
    p_detect.add_argument("--save", action="store_true", help="write config/axis_convention.json")
    p_detect.add_argument("--confirm", action="store_true",
                          help="mark the saved convention as visually confirmed by you")

    p_show = sub.add_parser("show", help="normalise one capture and print what happened")
    p_show.add_argument("path")
    p_show.add_argument("--origin", default="centroid", choices=ORIGIN_MODES)
    p_show.add_argument("--scale", default="centroid_size", choices=SCALE_MODES)

    args = parser.parse_args(argv)
    ensure_dirs()

    if args.command == "detect":
        captures = load_all(Path(args.root))
        if not captures:
            print(f"No loadable captures under {args.root}.")
            print("Export captures from the iOS app into data/raw/<participant_id>/ first.")
            return 1
        convention = detect_axis_convention(captures)
        print(f"Detected from {len(captures)} capture(s):\n")
        print(convention.describe())
        print("\nEvidence:")
        print(json.dumps(convention.evidence, indent=2))
        margin = convention.evidence.get("left_right_margin", 0)
        if isinstance(margin, (int, float)) and margin < 2.0:
            print("\nWARNING: the left-right axis was not clearly separated from the others")
            print("(margin < 2x). Inspect the mesh in the 3D viewer before trusting this.")
        if args.save:
            convention.confirmed_by_user = bool(args.confirm)
            path = convention.save()
            print(f"\nSaved to {path}")
            if not args.confirm:
                print("Confirm it visually (python -m src.visualization <capture> --frame),")
                print("then rerun with --save --confirm.")
        else:
            print("\n(dry run -- pass --save to write config/axis_convention.json)")
        return 0

    capture = load_capture(Path(args.path))
    config = NormalizationConfig(origin=args.origin, scale=args.scale)
    face = normalize_capture(capture, config=config)
    print(f"{face.key}")
    print(f"  origin mode      : {face.origin_mode}")
    print(f"  origin offset (m): {np.round(face.origin_offset_m, 5).tolist()}")
    print(f"  scale mode       : {face.scale_mode}")
    print(f"  scale reference  : {face.scale_reference_m:.6f} m")
    print(f"  side resolved    : {face.side_resolved}")
    lo, hi = face.vertices.min(axis=0), face.vertices.max(axis=0)
    print(f"  normalised bbox  : x[{lo[0]:+.3f},{hi[0]:+.3f}] y[{lo[1]:+.3f},{hi[1]:+.3f}] z[{lo[2]:+.3f},{hi[2]:+.3f}]")
    for note in face.notes:
        print(f"  note: {note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
